version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: bombolero_db
    environment:
      POSTGRES_DB: bombolero_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
